initramfs/config: ask about which Debian suite and mirror to use

diff --git a/initramfs/config b/initramfs/config
--- a/initramfs/config
+++ b/initramfs/config
@@ -14,6 +14,8 @@
 #    add leds udev rule
 
 mp=/tmp/newroot
+default_debian_suite=buster
+default_debian_mirror="http://httpredir.debian.org/debian"
 
 set_host() {
     case `hostname` in
@@ -30,6 +32,33 @@ set_host() {
 	* ) hostname $h
     esac
     return 1
+}
+
+set_debian() {
+	while [ -z "$debian_suite" ]; do
+		read -p "Which Debian suite do you want to install? (jessie | stretch | buster | bullseye | sid) [buster] " debian_suite
+		case "$debian_suite" in
+			"" ) debian_suite="$default_debian_suite" ;;
+			jessie | stretch | buster | bullseye | sid ) ;;
+			* ) echo "Unknown debian suite. Please enter one of the above choices."
+		esac
+	done
+	while [ -z "$debian_mirror" ]; do
+		read -p "Which Debian mirror do you want to use? [$default_debian_mirror]" debian_mirror
+		debian_mirror="${debian_mirror%/}"
+		case "$debian_mirror" in
+			"" ) debian_mirror="$default_debian_mirror" ;;
+			* )
+				echo -n "Validating mirror URL ... "
+				if wget -q --spider "$debian_mirror/debian/dists/$debian_suite/Release.gpg"; then
+					echo "OK."
+				else
+					echo "ERROR, please enter a valid Debian mirror URL."
+					debian_mirror=
+				fi
+		esac
+	done
+
 }
 
 check_net() {
@@ -146,7 +175,7 @@ bootstrap() {
     fi
     PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH
     export PATH
-    debootstrap --arch=mipsel --include=vim,openssh-server,ntpdate,cron,locales,udev,fake-hwclock,mtd-utils,ca-certificates,apt-transport-https,vlan,libnl-3-200,libnl-genl-3-200 stretch $mp http://httpredir.debian.org/debian || exit 1
+    debootstrap --arch=mipsel --include=vim,openssh-server,ntpdate,cron,locales,udev,fake-hwclock,mtd-utils,ca-certificates,apt-transport-https,vlan,libnl-3-200,libnl-genl-3-200 "$debian_version" "$mp" "$debian_mirror" || exit 1
     return 1
 }
 
@@ -223,7 +252,7 @@ fixup() {
     return 0
 }
 
-until set_host && set_passwd && set_net && set_time && create_filesystem && bootstrap && fixup; do
+until set_host && set_debian && set_passwd && set_net && set_time && create_filesystem && bootstrap && fixup; do
     :
 done
 
