mkinitramfs: move existence check into script.
"gbmake firmware" currently only runs mkinitramfs if it doesn't exist,
or doesn't have an 'init' file.

Change this to do the test inside the script and pass "-f" when we
explicitly want to recreate the initramfs.

As mkinitramfs also makes the files list which lives in the object
directory, it is easy for the files list to be removed while 'init'
still exists, so "gbmake firmware" might not restore the files list.

Now "gbmake firmware" will always create the files list if it doesn't
exist, and will still create rest of the initramfs if it doesn't exist.

"gbmake initramfs" will unconditionally make both.

Signed-off-by: NeilBrown <neil@brown.name>

diff --git a/scripts/mkinitramfs b/scripts/mkinitramfs
--- a/scripts/mkinitramfs
+++ b/scripts/mkinitramfs
@@ -9,16 +9,18 @@
 # It is not intended to be used directly - use "gbmake initramfs"
 #
 usage() {
-    echo >&2 "Usage: mkinitramfs target-directory file-for-device-list"
+    echo >&2 "Usage: mkinitramfs [-f] target-directory file-for-device-list"
     exit 2
 }
 
+force=
+if [ " $1" = " -f" ]; then
+    force=yes
+    shift
+fi
+
 case $# in
     2 ) dir=$1 devlist=$2
-        if [ ! -d "$dir" ]; then
-            echo >&2 "$dir does not exist".
-            usage
-        fi
     ;;
     * ) usage
 esac
@@ -119,7 +121,8 @@ if [ ! -d "$gbtools/scripts" ]; then
     exit 1
 fi
 
-cat > $devlist <<- END
+if [ -n "$force" -o ! -s $devlist ] ; then
+    cat > $devlist <<- END
 	dir /dev 755 0 0
 	nod /dev/console 600 0 0 c 5 1
 	nod /dev/null 666 0 0 c 1 3
@@ -136,7 +139,8 @@ cat > $devlist <<- END
 	dir /tmp 777 0 0
 	dir /mnt 755 0 0
 	dir /mnt/root 755 0 0
-END
+	END
+fi
 
 add_optional=yes
 if grep CONFIG_DTB_GNUBEE._UBOOT=y "$GNUBEE_KERNEL_OBJECTS/.config" > /dev/null 2>&1; then
@@ -144,7 +148,17 @@ if grep CONFIG_DTB_GNUBEE._UBOOT=y "$GNUBEE_KERNEL_OBJECTS/.config" > /dev/null 
 fi
 
 builddir=`realpath "$GNUBEE_BUILD_DIR"`
-cd $dir
+
+if [ -n "$force" -a -f $dir/init ]; then
+    # Already exists, skip
+    exit 0
+fi
+rm -rf "$dir"
+mkdir "$dir" || {
+    echo >&2 "mkinitramfs: cannot create $dir"
+    exit 1
+}
+cd "$dir"
 
 case `realpath .` in
     /*/*/* ) : ok ;;
