mkinitramfs: quote variables where possible

diff --git a/scripts/mkinitramfs b/scripts/mkinitramfs
--- a/scripts/mkinitramfs
+++ b/scripts/mkinitramfs
@@ -15,7 +15,7 @@ usage() {
 }
 
 case $# in
-	2 ) dir=$1 devlist=$2
+	2 ) dir="$1" devlist="$2"
 		if [ ! -d "$dir" ]; then
 			echo >&2 "$dir does not exist".
 			usage
@@ -24,16 +24,16 @@ case $# in
 	* ) usage
 esac
 
-case `uname -m` in
+case "`uname -m`" in
 	mips ) remote=eval ;;
 	* ) 
 	    if [ -d "$GNUBEE_BUILD_DIR/deb/chroot" ]; then
 		remote=from_chroot
 	    elif [ -n "$GNUBEE_SSH_HOST" ]; then
 		remote="ssh -x $GNUBEE_SSH_HOST"
-		case `$remote uname -m` in
+		case "`$remote uname -m`" in
 		    mips ) : success ;;
-		    * ) echo >&2 $GNUBEE_SSH_HOST no accessible or not mips; exit 1
+		    * ) echo >&2 "E: $GNUBEE_SSH_HOST not accessible or not mips"; exit 1
 		esac
 	    else
 		echo 'Please run on a gnubee, or provide GNUBEE_SSH_HOST, or "gbmake chroot"'
@@ -42,27 +42,27 @@ case `uname -m` in
 esac
 
 from_chroot() {
- ch=$GNUBEE_BUILD_DIR/deb/chroot
+ ch="$GNUBEE_BUILD_DIR/deb/chroot"
  if [ "$2" = "which" ]; then
-	for p in /sbin /usr/sbin `echo $PATH | tr : ' '`; do
-	    if [ -f $ch/$p/$3 ]; then
-		echo $p/$3
+	for p in /sbin /usr/sbin `echo "$PATH" | tr : ' '`; do
+	    if [ -f "$ch/$p/$3" ]; then
+		echo "$p/$3"
 		return
 	    fi
 	done
 	return
  fi
- if [ "$1" = cat ]; then
+ if [ "$1" = "cat" ]; then
 	if [ -e "$ch$2" ]; then
-		cat $ch$2
+		cat "$ch$2"
 	else
-		cat $ch/usr$2
+		cat "$ch/usr$2"
 	fi
 	return
  fi
 
- if [ "$1" = ldd ]; then
-    strings - $ch$2 | grep -a '\.so\.[0-9.]*$' | while read b; do
+ if [ "$1" = "ldd" ]; then
+    strings - "$ch$2" | grep -a '\.so\.[0-9.]*$' | while read b; do
 	for d in /lib/mipsel-linux-gnu /usr/lib/mipsel-linux-gnu ; do	
 	  if [ -f "$ch$d/$b" ]; then echo " stuff $d/$b (mess)";  fi
 	done
@@ -73,8 +73,8 @@ from_chroot() {
 	# do this after boot
 	return
  fi
- if [ "$1" = dropbearkey ]; then
-   a=`which 2> /dev/null dropbearkey`
+ if [ "$1" = "dropbearkey" ]; then
+   a="`which 2> /dev/null dropbearkey`"
    if [ -n "$a" ]; then
 	eval "$*"
    fi
@@ -82,26 +82,26 @@ from_chroot() {
  fi
  case "$*" in
     *debootstrap* )
-	(cd $ch ; tar 2> /dev/null cf - usr/sbin/debootstrap usr/share/debootstrap usr/share/keyrings/debian-archive-keyring.gpg )
+	(cd "$ch" ; tar 2> /dev/null cf - usr/sbin/debootstrap usr/share/debootstrap usr/share/keyrings/debian-archive-keyring.gpg )
 	;;
      *lib/terminfo*echo* )
-	( cd $ch; [ -d lib/terminfo ] && echo lib || echo usr/lib )
+	( cd "$ch"; [ -d lib/terminfo ] && echo "lib" || echo "usr/lib" )
 	;;
-    * ) echo >&2 ERROR cannot run command with chroot: "$*"
+    * ) echo >&2 "E: cannot run command with chroot: $*"
 	exit 1
  esac
 }
 
-prog=$0
-if [ -L "$prog" ]; then prog=`readlink $prog`; fi
-gbtools=`realpath $(dirname $prog)/..`
+prog="$0"
+if [ -L "$prog" ]; then prog="`readlink $prog`"; fi
+gbtools="`realpath "$(dirname "$prog")/.."`"
 
 if [ ! -d "$gbtools/scripts" ]; then
-	echo >&2 Cannot find scripts in $gbtools
+	echo >&2 "Cannot find $gbtools/scripts"
 	exit 1
 fi
 
-cat > $devlist <<- END
+cat > "$devlist" <<- END
 	dir /dev 755 0 0
 	nod /dev/console 600 0 0 c 5 1
 	nod /dev/null 666 0 0 c 1 3
@@ -125,12 +125,12 @@ if grep CONFIG_DTB_GNUBEE._UBOOT=y "$GNUBEE_KERNEL_OBJECTS/.config" > /dev/null 
     add_optional=no
 fi
 
-builddir=`realpath "$GNUBEE_BUILD_DIR"`
-cd $dir
+builddir="`realpath "$GNUBEE_BUILD_DIR"`"
+cd "$dir"
 
-case `realpath .` in
+case "`realpath .`" in
 	/*/*/* ) : ok ;;
-	* ) echo >&@ Refusing to create initramfs at such a high-level directory: `realpath .`
+	* ) echo >&@ "Refusing to create initramfs at such a high-level directory: `realpath .`"
 		exit 2;
 esac
 
@@ -143,12 +143,12 @@ ln -s ../lib usr/lib
 ln -s /proc/mounts etc/mtab
 
 # Debian moved some things from /lib to /usr/lib... makes life awkward.
-# terminfo is each to check..
-LIB=$($remote 'cd /; [ -d lib/terminfo ] && echo lib || echo usr/lib')
+# terminfo is easy to check..
+LIB="$($remote 'cd /; [ -d lib/terminfo ] && echo lib || echo usr/lib')"
 
 # cfdisk need terminfo - provide one.
 mkdir -p etc/terminfo/l
-$remote cat /$LIB/terminfo/l/linux > etc/terminfo/l/linux
+$remote cat "/$LIB/terminfo/l/linux" > etc/terminfo/l/linux
 
 # lvm need to know not to use udev
 # cribbed from https://wiki.gentoo.org/wiki/Custom_Initramfs#LVM
@@ -184,14 +184,14 @@ fi
 
 # install essential binaries
 for b in busybox findfs; do
-    path=`$remote PATH=/bin:/sbin:/usr/sbin:$PATH which $b 2> /dev/null`
+    path="`$remote "PATH=/bin:/sbin:/usr/sbin:$PATH" which "$b" 2> /dev/null`"
     if [ -z "$path" ]; then
 	echo "Please install $b"
 	exit 1;
     fi
     echo "## Install $path"
-    b=`basename $path`
-    $remote cat "$path" > bin/$b ; chmod 755 bin/$b
+    b="`basename "$path"`"
+    $remote cat "$path" > "bin/$b" ; chmod 755 "bin/$b"
     libs="$libs `$remote ldd "$path" |sed -n -e 's,^.*[ 	]\(/[^ ]*\) (.*$,\1,p'`"
 done
 
@@ -212,10 +212,10 @@ if [ -f bin/debootstrap ]; then
 	debootstrap_bins="$debootstrap_bins perl"
     else
 	echo "## building pkgdetails"
-	T=/tmp/.gb-built-$$
-	(cd $gbtools/pkgdetails; tar cf - . ) |
-	    $remote "rm -rf $T ; mkdir -p $T; cd $T; tar xf -; cc -Wno-implicit-function-declaration -o pkgdetails pkgdetails.c"
-	$remote cat $T/pkgdetails > usr/share/debootstrap/pkgdetails
+	T="/tmp/.gb-built-$$"
+	(cd "$gbtools/pkgdetails"; tar cf - . ) |
+	    $remote "rm -rf "$T" ; mkdir -p "$T"; cd "$T"; tar xf -; cc -Wno-implicit-function-declaration -o pkgdetails pkgdetails.c"
+	$remote cat "$T/pkgdetails" > usr/share/debootstrap/pkgdetails
 	chmod 755 usr/share/debootstrap/pkgdetails
     fi
 else
@@ -225,13 +225,13 @@ fi
 for b in blkid cryptsetup mdadm dropbear dbclient fsck.ext4 xfs_repair lvm \
 	btrfs \
 	evtest ntpdate passwd $debootstrap_bins ; do
-    path=`$remote PATH=/sbin:/usr/sbin:$PATH which $b 2> /dev/null`
+    path="`$remote "PATH=/sbin:/usr/sbin:$PATH" which "$b" 2> /dev/null`"
     if [ -z "$path" ]; then
 	echo $"$b not found, not installing"
     else
 	echo "## Install $path"
-	b=`basename $path`
-	$remote cat "$path" > bin/$b ; chmod 755 bin/$b
+	b="`basename $path`"
+	$remote cat "$path" > "bin/$b" ; chmod 755 "bin/$b"
 	libs="$libs `$remote ldd "$path" |sed -n -e 's,^.*[ 	]\(/[^ ]*\) (.*$,\1,p'`"
     fi
 done
@@ -240,16 +240,16 @@ if [ -f bin/dropbear ]; then
     # dropbear needs some extra configuration
     echo '## configuring dropbear'
     mkdir etc/dropbear
-    if [ ! -f $builddir/dropbear/dropbear_ecdsa_host_key ]; then
-	mkdir -p $builddir/dropbear
+    if [ ! -f "$builddir/dropbear/dropbear_ecdsa_host_key" ]; then
+	mkdir -p "$builddir/dropbear"
 	$remote "dropbearkey -t ecdsa -f /tmp/drop$$.key >&2;
-		 cat /tmp/drop$$.key" >  $builddir/dropbear/dropbear_ecdsa_host_key
+		 cat /tmp/drop$$.key" >  "$builddir/dropbear/dropbear_ecdsa_host_key"
     fi
-    cp $builddir/dropbear/* etc/dropbear
-    echo passwd: files >> etc/nsswitch.conf
-    echo group: files >> etc/nsswitch.conf
-    echo > etc/passwd root:x:0:0:root:/:/bin/sh
-    echo > etc/group  root:x:0:
+    cp "$builddir/dropbear/*" etc/dropbear
+    echo "passwd: files" >> etc/nsswitch.conf
+    echo "group: files" >> etc/nsswitch.conf
+    echo "root:x:0:0:root:/:/bin/sh" > etc/passwd
+    echo "root:x:0:" > etc/group
     echo 'PATH=.:/bin; export PATH' > etc/profile
     # root password is GnuBee
     echo > etc/shadow 'root:$6$l80E2NNrh32z0N$HX1nhaV6TcdM3OcMm8PVyzQZAl6c9Q2GYugdS9MuDcG6NkxW3eLCvLbw05tMKkbyRlieU1QeZ4tngZpaS9Fnf0::0:99999:7:::'
@@ -257,26 +257,26 @@ if [ -f bin/dropbear ]; then
     if [ -f bin/passwd ]; then
 	# need pam modules too
 	echo 'passwd password required pam_unix.so sha512' > etc/pam.conf
-	mkdir -p $LIB/mipsel-linux-gnu/security
-	path=$LIB/mipsel-linux-gnu/security/pam_unix.so
-	$remote cat /$path > $path
+	mkdir -p "$LIB/mipsel-linux-gnu/security"
+	path="$LIB/mipsel-linux-gnu/security/pam_unix.so"
+	$remote cat "/$path" > "$path"
 	libs="$libs `$remote ldd "/$path" |sed -n -e 's,^.*[ 	]\(/[^ ]*\) (.*$,\1,p'`"
     fi
 fi
 
 
 # ntpdate need to find the ntp service
-echo ntp 123/tcp >> etc/services
-echo ntp 123/udp >> etc/services
+echo "ntp 123/tcp" >> etc/services
+echo "ntp 123/udp" >> etc/services
 
 fi
 
 # Now make sure we have all the libraries we need.
 for lib in $libs; do
-	if [ ! -f .$lib ]; then
-		echo '## Adding' $lib
-		mkdir -p `dirname .$lib`
-		$remote cat $lib > .$lib ; chmod +x .$lib
+	if [ ! -f ".$lib" ]; then
+		echo "## Adding $lib"
+		mkdir -p "`dirname ".$lib"`"
+		$remote cat "$lib" > ".$lib" ; chmod +x ".$lib"
 	fi
 done
 
@@ -284,12 +284,12 @@ done
 $remote busybox --list |
   while read a;
   do
-     [ -e bin/$a ] || ln -s busybox bin/$a
+     [ -e "bin/$a" ] || ln -s busybox "bin/$a"
   done
 
 # copy in some scripts
-for i in $gbtools/initramfs/*
+for i in "$gbtools"/initramfs/*
 do
-	echo "## Install script `basename $i`"
-	cp -r $i .
+	echo "## Install script `basename "$i"`"
+	cp -r "$i" .
 done
